In [1]:
'''
Question:N queens problem 
Author:fukaiwen
Data:2021/10/7
'''

'\nQuestion:N queens problem \nAuthor:fukaiwen\nData:2021/10/7\n'

In [5]:
import numpy as np
import time
class NQueens:
    
    def __init__(self,number):
        #number为皇后的数量
        self.number=number
        self.board=np.zeros((number,number))
        self.chess_puted = []
        #将棋子下在(m,n)的代价
        self.cost=(number*number)*np.ones((number,number))

    #检查(m,n)是否可以放置皇后    
    def check_chess(self, m, n):
        if len(self.chess_puted)==0:
            #棋盘为空则(m,n)处一定可以放置皇后
            return True
        else:
            #棋盘非空，判定是否会相互攻击
            coordinate = np.array([m, n])
            for i in range(len(self.chess_puted)):
                # 坐标之差
                diff = coordinate-self.chess_puted[i]
                # 在(m,n)放置皇后之后，是否会与已放置的皇后是否相互攻击
                if diff[0] != diff[1] and diff[0] != -diff[1] and diff[0] != 0 and diff[1] != 0:
                    continue
                else:
                #相互攻击则该位置不能放置
                    return False
        return True
               
    #计算代价
    def cost_f(self,m,n):
        cost=0
        row,col=m,n
        while row<self.number and col>-1:
            row+=1
            col-=1
            cost+=1
        row,col=m,n
        while row<self.number and col<self.number:
            row+=1
            col-=1
            cost+=1
        return cost
    
    #启发式搜索
    def dfs_cost(self, m):
        for n in range(self.number):
            if self.check_chess(m, n):
                self.cost[m,n] =self.cost_f(m, n)
        while self.cost.sum(axis=1)[m] != self.number**3:
            n=np.argmin(self.cost, axis=1)[m]
            self.board[m, n] = 1
            self.chess_puted.append([m, n])
            self.cost[m][n]=self.number*self.number
            if m+1 == self.number:
                print("启发式求解:")
                print("棋盘结果")
                print(self.board)
                return 
            self.dfs_cost(m + 1)
            self.board[m, n]=0
            #self.cost[m][n]=self.number*self.number
            self.chess_puted.remove([m, n])
        return
if __name__ == '__main__':
    ans=NQueens(8)
    #ans.dfs(0)
    #ans.__init__(8)
    ans.dfs_cost(0)




启发式求解:
棋盘结果
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]]
